routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', 'HomeController@index');
Route::get('/login', 'AuthController@showLoginForm')->name('showLoginForm');
Route::post('/login', 'AuthController@login')->name('login');
Route::get('/register', 'AuthController@showRegisterForm')->name('showRegisterForm');
Route::post('/register', 'AuthController@register')->name('register');
Route::get('/logout', 'AuthController@logout');
Route::get('post/{id}', 'PostController@show')->name('showPost');

Route::group(['middleware' => ['auth:web']], function () {



    Route::get('create-post', 'PostController@create')->name('createPost');
    Route::post('save-post', 'PostController@store')->name('savePost');
    Route::get('edit-post/{id}', 'PostController@edit')->name('editPost');
    Route::post('update-post/{id}', 'PostController@update')->name('updatePost');
    Route::post('delete-post/{id}', 'PostController@destroy')->name('deletePost');
    Route::post('add-comment', 'CommentController@addComment')->name('addComment');
    Route::post('delete-comment/{id}', 'CommentController@deleteComment')->name('deleteComment');
    Route::post('update-comment', 'CommentController@updateComment')->name('updateComment');
//    Route::resource('post', 'PostController');

});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Intervention\Image\Facades\Image;

class Post extends Model
{
    //
    use SoftDeletes;

    protected $table = 'posts';


    public $timestamps = true;

    protected $guarded = ['id'];

    public function user()
    {
        return $this->belongsTo(User::class);
    }
    public function comments()
    {
        return $this->hasMany(Comment::class)->where('parent',0);
    }
    public function allComments()
    {
        return $this->hasMany(Comment::class);
    }
    public function getCommentsCountAttribute()
    {
        return $this->hasMany(Comment::class)->count();
    }

}

app/Http/Controllers/Website/AuthController.php
<?php

namespace App\Http\Controllers\Website;

use App\Http\Requests\LoginRequest;
use App\Http\Requests\RegisterRequest;
use App\Setting;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class AuthController extends Controller
{
    //
    public function showLoginForm()
    {
//        dd(456);
        if (!auth()->check()) {
//            dd(567);
            return view('website.layouts.login');
        } else {
            return redirect('/');
        }
    }

    public function login(LoginRequest $request)
    {

//
        $user = User::where('email', $request->email)->first();
        if ($user) {
            if (Hash::check($request->password, $user->password)) {
                auth()->login($user);
                toastr()->success('Welcome Back');
                return redirect('/');
            } else {
                #wrong pass
                toastr()->error('Wrong password');
                return redirect()->back()->withInput($request->only('email'));
            }
        } else {
            #no user found
            toastr()->error('Wrong Email');
            return redirect()->back()->withInput($request->only('email'));
        }


    }

    public function showRegisterForm(User $model)
    {
        //
        if (!auth()->check()) {
            return view('website.layouts.register', compact('model'));
        } else {
            return redirect('/');
        }

    }

    public function register(RegisterRequest $request)
    {





        $request->merge(['password' => Hash::make($request->password)]);
        $row = User::create($request->except('password_confirmation'));
        if ($row) {
            toastr()->success('Save Done  Successfully');

            auth()->login($row);

            return redirect('/');
        }
        toastr()->error('Error try again');
        return back();

    }

    public function logout()
    {
        auth()->logout();

        return redirect('/');
    }




}

app/Http/Controllers/Website/CommentController.php
<?php

namespace App\Http\Controllers\Website;

use App\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    //

    public function addComment(Request $request)
    {
        //
//        return $request->all();

        $this->validate($request, [
//            'user_name' => 'required|unique:users,user_name',

            'comment' => 'required',


        ]);

//return  $images = $request->file('images');

        $row = Comment::create($request->all());
//        $client->roles()->sync($request->input('role'));

        toastr()->success('Save Done Successfully');
        return back();
    }

    public function deleteComment($id)
    {
        $row = Comment::where('id', $id)->where('user_id', auth()->user()->id)->first();
        if ($row) {
            $row->comments()->delete();
            $row->delete();

            toastr()->success('Delete  Done Successfully');
            return back();
        } else {
            toastr()->error('Error try again');
            return back();
        }

    }

    public function updateComment(Request $request)
    {
//        return $request->all();

        $row = Comment::where('id', $request->id)->where('user_id', auth()->user()->id)->first();
        if ($row) {
            $row->comment= $request->comment;
            $row->save();

            toastr()->success('Save  Done Successfully');
            return back();
        } else {
            toastr()->error('Error try again');
            return back();
        }

    }
}

app/Http/Controllers/Website/HomeController.php
<?php

namespace App\Http\Controllers\Website;


use App\Http\Controllers\Controller;
use App\Post;
use Illuminate\Http\Request;


class HomeController extends Controller
{
    //
    public function index(Request $request)
    {

        $rows = Post::latest();
        if ($request->filled('title')) {

            $rows->where('title', 'like', '%' . $request->title . '%');
        }
        if ($request->filled('date')) {

            $rows->whereDate('created_at', $request->date);
        }
        if ($request->filled('user_id')) {

            $rows->where('user_id', $request->user_id);
        }
        $rows=$rows->paginate(9);
        return view('website.index', compact('rows'));
    }
}

app/Http/Controllers/Website/PostController.php
<?php

namespace App\Http\Controllers\Website;

use App\City;


use App\Post;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Hash;


class PostController extends Controller
{
    //


    public function index(Request $request)
    {
        //
        return "aa";
        $rows = Post::latest();


        $rows = $rows->paginate(20);

        return view('website.post.index', compact('rows'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Post $model)
    {
//        return "asa";
        return view('website.post.create', compact('model'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
//        return $request->all();

        $this->validate($request, [

            'title' => 'required|max:255',
            'text' => 'required',


        ]);
        $request->merge(['user_id' => auth()->user()->id]);

        $row = Post::create($request->all());


        toastr()->success('Save Done Successfully');
        return redirect('/');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $row = Post::where('id', $id)->with('comments')->first();
//        return "dd";
        if ($row) {

            return view('website.post.show', compact('row'));
        }
        abort(404);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $model = Post::findOrFail($id);
        return view('website.post.edit', compact('model'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //

        $this->validate($request, [

            'title' => 'required|max:255',
            'text' => 'required',


        ]);

        $row = Post::where('id', $id)->where('user_id', auth()->user()->id)->first();
        $row->update($request->all());


//        $client->roles()->sync($request->role);
        toastr()->success('Save Done Successfully');
        return redirect('/');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
//return "ss";

        $row = Post::where('id', $id)->where('user_id', auth()->user()->id)->first();

        if ($row) {
            $row->allComments()->delete();


            $row->delete();

            toastr()->success('Delete  Done Successfully');
            return back();
        } else {
            toastr()->error('Error try again');
            return back();
        }


    }


}

resources/views/website/index.blade.php
@extends('website.layouts.main')
@section('content')
    @inject('user','App\User')

    <?php

    $users = $user->latest()->pluck('name', 'id')->toArray();

    ?>
    @push('style')
        <style>

            .post--text {
                overflow: hidden;
                text-overflow: ellipsis;
                display: -webkit-box;
                -webkit-line-clamp: 6;
                -webkit-box-orient: vertical;
            }
        </style>
    @endpush

    <div class="wrapper wrapper-content  animated fadeInRight blog">
        <div class="ibox-content m-b-sm border-bottom">

            {!! Form::open([
                  'method' => 'GET'
              ]) !!}

            <div class="row">

                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label" for="user_id">User Name</label>
                        {{Form::select('client_id', $users, request()->user_id, [
                            "class" => "form-control select2 " ,
                            "id" => "client_id",
                            "placeholder" => "User Name"
                        ])}}
                        {{--<input type="text" id="status" name="status" value="" placeholder="Status" class="form-control">--}}
                    </div>
                </div>
                <div class="col-sm-4">
                    <div class="form-group">
                        <label class="control-label" for="title">Title</label>
                        <input type="text" id="title" name="title" value="{{request()->title}}" placeholder="Title"
                               class="form-control">
                    </div>
                </div>

                <div class="col-md-4">
                    <div class="form-group ">
                        <label class="control-label" for="date">Date</label>
                        <div class="input-group date">

                            {!! Form::text('date',request()->date,[
                                'class' => 'form-control datepicker',
                                'placeholder' => 'Date'
                            ]) !!}
                            <span class="input-group-addon"><i class="fa fa-calendar"></i></span>
                        </div>
                    </div>
                </div>
            </div>

            <div class="row">


                <div class="clearfix"></div>
                <div class="row ">
                    <div class="col-sm-2  ">
                        <div class="form-group">
                            <label for="">&nbsp;</label>
                            <button type="submit" class="btn btn-flat  btn-primary btn-md">Search</button>
                        </div>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
        <div class="row">
            @if($rows->count()>0)

                @foreach($rows as $key=>$row)
                    <?php

                    $rem = $key % 3;
                    //                    echo $rem;
                    ?>

                    <div class="col-lg-4">

                        <div class="ibox">
                            <div class="ibox-title">
                                @if(auth()->check() and (auth()->user()->id== $row->user_id ))
                                    <a class="btn btn-primary btn-xs" href="{{route('editPost',$row->id)}}"><i class="fa fa-edit"></i> Edit
                                    </a>
                                    {{Form::open(array('method'=>'post','class'=>'delete pull-right','url'=>route('deletePost',$row->id) )) }}
                                    <button class="btn btn-danger btn-xs " type="submit"><i class="fa fa-trash-o"></i>
                                        Delete
                                    </button>
                                    {{Form::close()}}
                                @endif
                            </div>
                            <div class="ibox-content">
                                <a href="{{url('post/'.$row->id)}}" class="btn-link">
                                    <h2>
                                        {{$row->title}}
                                    </h2>
                                </a>
                                <div class="small m-b-xs">
                                    <strong>{{$row->user->name ?? '...'}}</strong> <span class="text-muted"><i
                                                class="fa fa-clock-o"></i> {{$row->created_at->diffForHumans()}}</span>
                                </div>
                                <p class="post--text">
                                    {{$row->text}}
                                </p>
                                <div class="row">

                                    <div class="col-md-6">


                                        <div><i class="fa fa-comments-o"> </i> {{$row->comments_count}} comments</div>


                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    @if($rem==2)
                        <div class="clearfix"></div>
                    @endif
                @endforeach
                <div class="clearfix"></div>
                <div class="text-center">
                    {!! $rows->appends(request()->except('page'))->links() !!}
                </div>
            @else
                <h2 class="text-center">لا يوجد بيانات</h2>
            @endif
        </div>


    </div>



@stop